# This file was generated by GoReleaser. DO NOT EDIT.
cask "cflio" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "a6099ba2cbf86bf0ce3ec4b085b4ad972886c59b156b7c85486f54f062215b92"
      url "https://github.com/178inaba/cflio/releases/download/v#{version}/cflio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "347924516c057c674ae000d5970798ea9b071bd10e3724d994c0742e745a036f"
      url "https://github.com/178inaba/cflio/releases/download/v#{version}/cflio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "05a24bb43dbcc94465170684339775e74d1484823a93395d7136c3b8d06f9bdf"
      url "https://github.com/178inaba/cflio/releases/download/v#{version}/cflio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1cf0e44ad77b71136fbcea267557839f3c9d206e89e433d5b3c404dfd90bf951"
      url "https://github.com/178inaba/cflio/releases/download/v#{version}/cflio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cflio"
  desc "Confluence Cloud CLI for AI coding agents: read and update page bodies through local files, losslessly, without the body passing through the model."
  homepage "https://github.com/178inaba/cflio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cflio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cflio"]
    end
  end

  # No zap stanza required
end
