# This file was generated by GoReleaser. DO NOT EDIT.
cask "cflio" do
  version "1.0.5"

  on_macos do
    on_arm do
      sha256 "f648db8e06c16abb9144eff46fde1070fa8fc42ffc8b1f7f2207e428e5425a62"
      url "https://github.com/178inaba/cflio/releases/download/v#{version}/cflio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "adce6178ffc44e391dde5b002e8760817e10e7cefffc03193b9f67267cbca8e2"
      url "https://github.com/178inaba/cflio/releases/download/v#{version}/cflio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7e4e6ef9e68f013021a016839121866af9c141fea52d954583abf7802096e9e1"
      url "https://github.com/178inaba/cflio/releases/download/v#{version}/cflio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c3fc353beaa8fb4126640dbc578abc1cef6c868533ed3af752f2677f8fc7f1c7"
      url "https://github.com/178inaba/cflio/releases/download/v#{version}/cflio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cflio"
  desc "Confluence Cloud CLI for AI coding agents: read and update page bodies through local files, losslessly, without the body passing through the model."
  homepage "https://github.com/178inaba/cflio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cflio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cflio"]
    end
  end

  # No zap stanza required
end
