# This file was generated by GoReleaser. DO NOT EDIT.
cask "cflio" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "962bd6cfc6c53956d60fabb2175c60da6b00bd83838bed8ef910924e667f1285"
      url "https://github.com/178inaba/cflio/releases/download/v#{version}/cflio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1a64d9d01444aafa88dfc8e0d340d0ed7cc974d19e5f0b6e7e02678331f47ce5"
      url "https://github.com/178inaba/cflio/releases/download/v#{version}/cflio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "65734c20fea52dbd25e7c9198b115130e8f252b557b73306537ebf135f206c54"
      url "https://github.com/178inaba/cflio/releases/download/v#{version}/cflio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "71df63afbf034acee1e4845cc6917b55af391b2e53bd75af35dbca478c589cb5"
      url "https://github.com/178inaba/cflio/releases/download/v#{version}/cflio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cflio"
  desc "Confluence Cloud CLI for AI coding agents: read and update page bodies through local files, losslessly, without the body passing through the model."
  homepage "https://github.com/178inaba/cflio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cflio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cflio"]
    end
  end

  # No zap stanza required
end
