# This file was generated by GoReleaser. DO NOT EDIT.
cask "rdsh" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "6a9f9f84d3bacaf7d4d36e1e7b54548781dbad8b5896844ab9d6dbf7199f46c0"
      url "https://github.com/178inaba/rdsh/releases/download/v#{version}/rdsh_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d34fa5d8b375907e7ac1f73ff224d59f7fd3a888f459aeec654787bb8ea232d"
      url "https://github.com/178inaba/rdsh/releases/download/v#{version}/rdsh_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1279d0b045224c5d318af987b4b028543ab10fb4c93813e53d7aecfe0fa8fc51"
      url "https://github.com/178inaba/rdsh/releases/download/v#{version}/rdsh_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c49bdd4fba65d4907aa2bd5160103bb8d86dcd8d3cb6632901b6b07c76e3c124"
      url "https://github.com/178inaba/rdsh/releases/download/v#{version}/rdsh_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rdsh"
  desc "Run ad-hoc SQL and manage saved queries on Redash from the command line: one command per round trip, built for AI coding agents."
  homepage "https://github.com/178inaba/rdsh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rdsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rdsh"]
    end
  end

  # No zap stanza required
end
