# This file was generated by GoReleaser. DO NOT EDIT.
cask "rdsh" do
  version "1.0.5"

  on_macos do
    on_arm do
      sha256 "dffb2b0495a54b4dffaf201ff5d31a08d1d76ffe533d4ffa5bbe39fcdaf49452"
      url "https://github.com/178inaba/rdsh/releases/download/v#{version}/rdsh_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9806db0f230b619575f131fff44b978d41333972b16f27396e453ad2883890a3"
      url "https://github.com/178inaba/rdsh/releases/download/v#{version}/rdsh_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "86ef742bce25c8cd9eebff2ca5de4bcb9667bb231b669a24d439344b914994f4"
      url "https://github.com/178inaba/rdsh/releases/download/v#{version}/rdsh_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8edf1388efeaff5c636347387efda5152d014334dada530bf370aa6b415b604a"
      url "https://github.com/178inaba/rdsh/releases/download/v#{version}/rdsh_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rdsh"
  desc "Run ad-hoc SQL and manage saved queries on Redash from the command line: one command per round trip, built for AI coding agents."
  homepage "https://github.com/178inaba/rdsh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rdsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rdsh"]
    end
  end

  # No zap stanza required
end
