# This file was generated by GoReleaser. DO NOT EDIT.
cask "rdsh" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "b17a57fd544dd6eb833c9345bed6e007f70126b56fbd6ebd08877eb06df33abf"
      url "https://github.com/178inaba/rdsh/releases/download/v#{version}/rdsh_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "28769381afcd8bc7bf9ca625c955618050f9d99a8a7b6efc767b03f26e69943f"
      url "https://github.com/178inaba/rdsh/releases/download/v#{version}/rdsh_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c55aa822b8ecff7e80867ad6d673c6d4dce5a37e6c9fb86af5613931cee5891a"
      url "https://github.com/178inaba/rdsh/releases/download/v#{version}/rdsh_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f8e34ecc68b339363525ad1967acffffbaa1c663a7c764de121446ae98d3da22"
      url "https://github.com/178inaba/rdsh/releases/download/v#{version}/rdsh_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rdsh"
  desc "Run ad-hoc SQL and manage saved queries on Redash from the command line: one command per round trip, built for AI coding agents."
  homepage "https://github.com/178inaba/rdsh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rdsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rdsh"]
    end
  end

  # No zap stanza required
end
