# This file was generated by GoReleaser. DO NOT EDIT.
cask "slio" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "9a4716356c70c98f9ff31e6591117b5127fbe9dd4a8fbf8b62ef35b3f72a7718"
      url "https://github.com/178inaba/slio/releases/download/v#{version}/slio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "39fc62ac5677e5ec51af243b30ad2b10228a4cacc75425b8b96fac514e718e20"
      url "https://github.com/178inaba/slio/releases/download/v#{version}/slio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "57b314c412cbb32c52f67f9fef04c83288e638d8d450669da7366a8d9cff55ea"
      url "https://github.com/178inaba/slio/releases/download/v#{version}/slio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "18807da99c57593bd466e56a4fe39d7227a8795a44a6c0a93b22996deeff1f0d"
      url "https://github.com/178inaba/slio/releases/download/v#{version}/slio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "slio"
  desc "Read-only Slack CLI for AI coding agents: fetch threads, channel history, and search results as AI-readable Markdown."
  homepage "https://github.com/178inaba/slio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slio"]
    end
  end

  # No zap stanza required
end
