# This file was generated by GoReleaser. DO NOT EDIT.
cask "slio" do
  version "1.0.4"

  on_macos do
    on_arm do
      sha256 "7b3ffbea70c21f6d49458c99291443fe3ec2f96f2705413821a73ab0797429f0"
      url "https://github.com/178inaba/slio/releases/download/v#{version}/slio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cf8e01ab5ede06602b69d327d037b9246d84acfb76ac3c806b6b4aa73e4ccecd"
      url "https://github.com/178inaba/slio/releases/download/v#{version}/slio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "376e56416a44909edbe918776033b4c3f807726717357b50aadc3390f6b1688d"
      url "https://github.com/178inaba/slio/releases/download/v#{version}/slio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "48a36c0d1fdedc5970326a6aca075402532293b9a8f10135c99024c7786cc519"
      url "https://github.com/178inaba/slio/releases/download/v#{version}/slio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "slio"
  desc "Read-only Slack CLI for AI coding agents: fetch threads, channel history, and search results as AI-readable Markdown."
  homepage "https://github.com/178inaba/slio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slio"]
    end
  end

  # No zap stanza required
end
