# This file was generated by GoReleaser. DO NOT EDIT.
cask "slio" do
  version "1.0.5"

  on_macos do
    on_arm do
      sha256 "b8986c78c888a3a732e1177cf43df0915a82d025d39df1395819cca82e08d58f"
      url "https://github.com/178inaba/slio/releases/download/v#{version}/slio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "406180698524a144cb25d03cfba8587ef97cf5e5352b822792e32e8b482941cf"
      url "https://github.com/178inaba/slio/releases/download/v#{version}/slio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "73fbb9baa76f3d88772f19ebae4474c504014ef451e69709c2dcd0df32ec6bf9"
      url "https://github.com/178inaba/slio/releases/download/v#{version}/slio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ea5e09e8b5b7cfc03ffaa77793f802b224dbabdd8546afe0fec945d4d86932bf"
      url "https://github.com/178inaba/slio/releases/download/v#{version}/slio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "slio"
  desc "Read-only Slack CLI for AI coding agents: fetch threads, channel history, and search results as AI-readable Markdown."
  homepage "https://github.com/178inaba/slio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slio"]
    end
  end

  # No zap stanza required
end
